name: code-freeze-check
on:
  push:
    branches:
      - acryl-main
  pull_request:
    branches:
      - acryl-main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  code-freeze-check:
    runs-on: ubuntu-latest
    steps:
      # Controlled through this secret https://github.com/acryldata/datahub-fork/settings/secrets/actions/SAAS_CODE_FREEZE_IN_PLACE
      # set to 0 to stop code freeze
      # set to 1 to start code freeze
      - name: Check freeze is in place
        run: |
          exit ${{ secrets.SAAS_CODE_FREEZE_IN_PLACE }}