name: Publish Datahub Client

on:
  workflow_run:
    workflows: ["build & test"]
    types:
      - completed

  release:
    types: [published, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  check-secret:
    runs-on: ubuntu-latest
# Disable check for now while test fails
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      publish-enabled: ${{ steps.publish-enabled.outputs.defined }}
    steps:
      - id: publish-enabled
        if: "${{ env.SIGNING_KEY != '' }}"
        run: echo "::set-output name=defined::true"
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [check-secret]
    if: needs.check-secret.outputs.publish-enabled == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
      - name: Get CodeArtifact Auth Token
        run: |
          echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain acryl --domain-owner 795586375822 --query authorizationToken --output text)" >> $GITHUB_ENV
          git remote add upstream https://github.com/datahub-project/datahub.git
          git fetch upstream --tags --force
      - name: publish datahub-client jar
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          CODEARTIFACT_AUTH_TOKEN: ${{ env.CODEARTIFACT_AUTH_TOKEN }}
        run: |
          echo signingKey=$SIGNING_KEY >> gradle.properties
          ./gradlew :metadata-integration:java:datahub-client:printVersion
          ./gradlew :metadata-integration:java:datahub-client:publish
